version: '3'

services:
  web:
    environment:
      - DEBUG=True
      - SECRET_KEY='1234'
      - DB_NAME=cms_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/CMS
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cms_db
