version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  test:
    docker:
      - image: circleci/python:3.8.10
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . env/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  build_and_test:
    jobs:
      - test
